---
name: Generate SBOM
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: The tag to use for generating SBOM.
        required: true
jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    environment: release
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: '#oss-releases'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Get github app token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Checkout tag
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.tag }}
          token: ${{ steps.gh-app-token.outputs.token }}
      - name: Slack notification
        uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        with:
          status: starting
          steps: ${{ toJson(steps) }}
          channel: ${{ env.SLACK_CHANNEL }}
          message: Starting generating sbom for ${{ github.repository }} with tag ${{ inputs.tag }}......
        if: always()
      - name: Run SBOM
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          upload-artifact-retention: 7
          upload-release-assets: false
          github-token: ${{ steps.gh-app-token.outputs.token }}
          output-file: openzeppelin-monitor-${{ inputs.tag }}-spdx.json
          artifact-name: openzeppelin-monitor-${{ inputs.tag }}-spdx.json
      - name: Upload Release Artifact
        env:
          GH_TOKEN: ${{ steps.gh-app-token.outputs.token }}
        run: gh release upload ${{ inputs.tag }} openzeppelin-monitor-${{ inputs.tag }}-spdx.json
      - name: SBOM attestation
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd  # main
        with:
          subject-path: ./openzeppelin-monitor-${{ inputs.tag }}-spdx.json
          github-token: ${{ steps.gh-app-token.outputs.token }}
      - name: Slack notification
        uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d # v2.1.0
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ env.SLACK_CHANNEL }}
          message: Generating sbom ${{ job.status }}
        if: always()
